extends Node

var list2 = {
	"あいさつ" : "greeting",
	"あかるい" : "bright",
	"あきらめる" : "to give up",
	"あの" : "that over there",
	"あぶない" : "dangerous",
	"あんぜん" : "safety",
	"いう | 言う" : "to say",
	"という" : "to be called",
	"いっしょうけんめい" : "as hard as one can",
	"いる" : "to need",
	"いれる" : "to put in",
	"うんてん" : "driving",
	"うんてんする" : "to drive",
	"えらぶ" : "to choose",
	"おうえんする" : "to support",
	"おおい" : "a lot",
	"おしえる" : "to teach",
	"おとな | 大人" : "adult",
	"おもいだす" : "to recall",
	"おもいで" : "memories",
	"おもう | 思う" : "to think",
	"おりる" : "to get off",
	"がいこく | 外国" : "foreign country",
	"がいこくご | 外国語" : "foreign language",
	"かたづける" : "to tidy up",
	"がっかりする" : "to be disappointed",
	"がっき" : "school term",
	"かならず" : "certainly",
	"かみ" : "paper",
	"かわる" : "to change",
	"かんけい" : "connection",
	"かんどうする" : "to be moved",
	"カンニングする" : "to cheat in a test",
	"きそく" : "rule",
	"きもちいい" : "to feel good",
	"きゅうしょく" : "meal provided by an organisation",
	"きょういく" : "education",
	"きょうかしょ" : "textbook",
	"きょうみ" : "interest",
	"きょうみがある" : "to be interested in",
	"きんじょ" : "neighbourhood",
	"くうき" : "air",
	"くらい" : "dark",
	"くらべる" : "to compare",
	"グループ" : "group",
	"けいざい" : "economy",
	"けす" : "to turn off",
	"けっか" : "result",
	"こうりゅうする" : "to interact",
	"こたえ" : "answer",
	"こたえる" : "to answer",
	"ことば" : "language",
	"ことわる" : "to reject",
	"この" : "this",
	"コミュニティ" : "community",
	"これから" : "from now on",
	"さいきん" : "recently",
	"さいご" : "last",
	"さいしょ" : "first",
	"さくぶん" : "essay",
	"さそう" : "to invite",
	"さびしい" : "lonely",
	"しけんにおちる" : "to fail an exam",
	"しけんにとおる" : "to pass an exam",
	"しけんをうける" : "to sit an exam",
	"しつもん" : "question",
	"しつもんする" : "to ask a question",
	"じどうはんばいき" : "vending machine",
	"しゅうがくりょこう" : "school trip",
	"しゅうかん" : "custom",
	"しふく" : "mufti",
	"じゆうじかん" : "leisure time",
	"しゅっしん" : "place of origin",
	"しゅわ | 手話" : "sign language",
	"じゅんび" : "preparation",
	"じゅんびする" : "to prepare",
	"しんじる" : "to believe",
	"しんぱいする" : "to worry",
	"すぐ" : "immediately",
	"すくない | 少ない" : "few",
	"すごす" : "to spend time",
	"ずっと" : "much more",
	"すてる" : "to throw away",
	"ストレス" : "stress",
	"せいかつ" : "way of life",
	"せいせき" : "results",
	"せつめい" : "explanation",
	"せつめいする" : "to explain",
	"せんしゅ" : "athlete",
	"そつぎょうしき" : "graduation ceremony",
	"そつぎょうする" : "to graduate",
	"その" : "that",
	"そら" : "sky",
	"たいいくさい" : "sports festival",
	"たすける" : "to help",
	"ただしい" : "correct",
	"たとえば" : "for example",
	"たのしみにする" : "to look forward to",
	"たのしむ" : "to enjoy",
	"たのむ" : "to request",
	"チーム" : "team",
	"つき | 月" : "moon",
	"つぎ" : "next",
	"つける" : "to turn on",
	"つつむ" : "to wrap",
	"テーマパーク" : "theme park",
	"てつだう" : "to give a hand",
	"でる" : "to attend",
	"でんき" : "electricity",
	"どうやって" : "in what manner",
	"どきどきする" : "to be nervous",
	"とくべつ" : "special",
	"どの" : "which",
	"ともだちができる | 友だちができる" : "to make a friend",
	"なくなる" : "to pass away",
	"なつかしい" : "to fondly remember",
	"なやむ" : "to be troubled",
	"ならぶ" : "to line up",
	"なれる" : "to become used to",
	"にている" : "to look alike",
	"にゅうがくする" : "to start school",
	"にゅうがくしき" : "welcoming ceremony",
	"にゅうがくしけん" : "entrance examination",
	"にんきがある" : "to be popular",
	"にんきがでる" : "to become popular",
	"ねだん" : "price",
	"はじめ" : "beginning",
	"はじめる" : "to start",
	"ばしょ" : "place",
	"はしる" : "to run",
	"はずかしい" : "embarrassed",
	"はなしあう" : "to discuss",
	"はらう" : "to pay",
	"ひきわけ" : "draw",
	"びっくりする" : "to be surprised",
	"ひつよう" : "necessary",
	"ふえる" : "to increase",
	"ふくろ" : "sack",
	"プラスチック" : "plastic",
	"ふるさと" : "place you belong",
	"へらす" : "to decrease",
	"へんじ" : "response",
	"へんじする" : "to respond",
	"ほか" : "other",
	"ほし" : "star",
	"ほとんど" : "almost all",
	"ボランティア" : "volunteer",
	"ほんとう" : "true",
	"まいつき" : "every month",
	"まいねん | まいとし" : "every year",
	"まもる" : "to obey",
	"むり" : "impossible",
	"めずらしい" : "rare",
	"メンバー" : "member",
	"もちろん" : "of course",
	"もったいない" : "wasteful",
	"もんだい" : "problem",
	"やめる" : "to quit",
	"ゆっくりする" : "to relax",
	"リサイクルする" : "to recycle",
	"わかい" : "young",
	"わくわくする" : "to be excited",
	"わらう" : "to laugh"
}
