extends Node

var list3 = {
	"アイデンティティ" : "identity",
	"アウトドア" : "outdoors",
	"あがる | 上がる" : "to rise",
	"あんないする" : "to guide",
	"いけん" : "opinion",
	"いちにちじゅう | 一日中" : "all day",
	"いつか" : "someday",
	"いつでも" : "any time",
	"いみん" : "immigrant",
	"インフルエンサー" : "influencer",
	"うえる" : "to plant",
	"えいきょう" : "influence",
	"えいきょうする" : "to have an influence",
	"エコ（な）" : "ecology",
	"おと | 音" : "sound",
	"おとしより" : "elderly person",
	"おもいやり | 思いやり" : "empathy",
	"おんせん" : "hot spring",
	"おんだんか" : "warming",
	"かいしゃ | 会社" : "company",
	"かえる" : "to change",
	"かざん | 火山" : "volcano",
	"ガソリン" : "petrol",
	"かみ(さま)" : "deity",
	"かんがえる" : "to consider",
	"かんきょう" : "environment",
	"かんこうきゃく" : "tourist",
	"かんこうち" : "tourist spot",
	"かんしんがある" : "to be concerned about",
	"キウイ" : "kiwifruit",
	"きおん" : "temperature",
	"きこう" : "climate",
	"きっと" : "surely",
	"キャラクター" : "character",
	"きゅうりょう" : "salary",
	"きょうりょくする" : "to work together",
	"きをつける | 気をつける" : "to pay attention",
	"けいかく" : "plan",
	"けいかくをたてる" : "to make plans",
	"けいけん" : "experience",
	"けいけんする" : "to experience",
	"げんいん" : "cause",
	"こうがい" : "pollution",
	"こうじょう" : "factory",
	"こうずい" : "flood",
	"こうばん" : "police box",
	"こころ | 心" : "heart",
	"こと" : "matter",
	"こまる" : "to be troubled",
	"こわれる" : "to break",
	"コンポスト" : "compost",
	"さがす" : "to look for",
	"さがる | 下がる" : "to lower",
	"さべつ" : "discrimination",
	"さべつする" : "to discriminate",
	"さんぎょう" : "industry",
	"さんせいする" : "to agree",
	"ジェンダー" : "gender",
	"じしん" : "earthquake",
	"しゅと" : "capital city",
	"しげん" : "resource",
	"しぜん" : "nature",
	"しま | 島" : "island",
	"しまぐに | 島国" : "island country",
	"しゃかい | 社会" : "society",
	"じゆう | 自由" : "freedom",
	"しゅうきょう" : "religion",
	"じゅうぶん | 十分" : "enough",
	"じょうほう" : "information",
	"しょうらい" : "one’s future",
	"しらべる" : "to investigate",
	"じんこう | 人口" : "population",
	"せいかつする" : "to lead a life",
	"せいふ" : "government",
	"せかい" : "world",
	"せきにん" : "responsibility",
	"せだい" : "generation",
	"ぜったい(に)" : "definitely",
	"だいじにする" : "to value",
	"たいふう" : "typhoon",
	"たすけあう" : "to help each other",
	"ただ" : "free of charge",
	"たぶん" : "probably",
	"たぶんか | 多文化" : "multicultural",
	"ためる" : "to save",
	"だれか" : "someone",
	"だれでも" : "whoever",
	"だれも" : "no one",
	"ちきゅう" : "Earth",
	"ちほう" : "region",
	"つゆ" : "rainy season",
	"できるだけ" : "as much as possible",
	"でぐち | 出口" : "exit",
	"テクノロジー" : "technology",
	"とかい" : "urban area",
	"とくに" : "especially",
	"どこか" : "somewhere",
	"どこでも" : "anywhere",
	"どこも" : "nowhere",
	"どりょくする" : "to make an effort",
	"なおす" : "repair",
	"なにか | 何か" : "something",
	"なにも | 何も" : "nothing",
	"なんでも | 何でも" : "anything",
	"について" : "regarding",
	"によって" : "depending on",
	"のかわりに" : "instead of",
	"のりかえる" : "to change",
	"はくぶつかん" : "museum",
	"はっきり" : "clearly",
	"はんたい" : "opposite",
	"はんたいする" : "to oppose",
	"ビジネス" : "business",
	"ひろう" : "pick up",
	"ふる" : "to fall",
	"フレンドリー（な）" : "friendly",
	"へいわ | 平和" : "peace",
	"ポップカルチャー" : "pop culture",
	"みつける | 見つける" : "to find",
	"もういちど" : "once more",
	"もつ" : "to have",
	"もの" : "thing",
	"やっぱり" : "as I thought",
	"やる" : "to do",
	"ゆめ" : "dream",
	"ロボット" : "robot",
	"わける | 分ける" : "to divide"
}
